routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCatalogItemController;
use App\Http\Controllers\Admin\AdminIngredientController;
use App\Http\Controllers\Admin\AdminPastryController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Public routes
 */
Route::get('/', fn() => view('index'))->name('index');

/**
 * Admin routes
 */
Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {

    Route::get('/', fn() => redirect()->route('admin.dashboard'));

    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');

    Route::prefix('profile')->name('profile.')->group(function(){
        Route::get('/', [AdminProfileController::class, 'edit'])->name('edit');
        Route::patch('/', [AdminProfileController::class, 'update'])->name('update');
        Route::delete('/', [AdminProfileController::class, 'destroy'])->name('destroy');
    });

    Route::resource('pastries', AdminPastryController::class, ['except'=> ['show']]);
    Route::resource('ingredients', AdminIngredientController::class, ['except'=> ['show']]);
    Route::resource('catalog-items', AdminCatalogItemController::class, ['except'=> ['show']]);
});

/**
 * Auth routes
 */
require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <ul class="grid grid-cols-2 gap-6 text-center">
                        <li>
                            <a class="block py-8 px-12 border border-gray-200 rounded-lg font-semibold text-xl hover:bg-gray-100" href="{{ route('admin.pastries.index') }}">{{ __('Pastries management') }}</a>
                        </li>
                        <li>
                            <a class="block py-8 px-12 border border-gray-200 rounded-lg font-semibold text-xl hover:bg-gray-100" href="{{ route('admin.ingredients.index') }}">{{ __('Ingredients management') }}</a>
                        </li>
                        <li>
                            <a class="block py-8 px-12 border border-gray-200 rounded-lg font-semibold text-xl hover:bg-gray-100" href="{{ route('admin.catalog-items.index') }}">{{ __('Catalog management') }}</a>
                        </li>
                        <li>
                            <a class="block py-8 px-12 border border-gray-200 rounded-lg font-semibold text-xl hover:bg-gray-100" href="{{ route('admin.profile.edit') }}">{{ __('User profile') }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>