routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCatalogItemController;
use App\Http\Controllers\Admin\AdminIngredientController;
use App\Http\Controllers\Admin\AdminPastryController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Public routes
 */
Route::get('/', fn() => view('index'))->name('index');

/**
 * Admin routes
 */
Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {

    Route::get('/', fn() => redirect()->route('admin.dashboard'));

    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');

    Route::prefix('profile')->name('profile.')->group(function(){
        Route::get('/', [AdminProfileController::class, 'edit'])->name('edit');
        Route::patch('/', [AdminProfileController::class, 'update'])->name('update');
        Route::delete('/', [AdminProfileController::class, 'destroy'])->name('destroy');
    });

    Route::resource('pastries', AdminPastryController::class, ['except'=> ['show']]);
    Route::resource('ingredients', AdminIngredientController::class, ['except'=> ['show']]);
    Route::resource('catalog-items', AdminCatalogItemController::class, ['except'=> ['show']]);
});

/**
 * Auth routes
 */
require __DIR__.'/auth.php';

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Ingredient extends Model
{
    use HasFactory;
    
    /**
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'unit_of_measurement',
    ];

    /**
     * @var array<int, string>
     */
    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    /**
     * @return BelongsToMany
     */
    public function pastries(): BelongsToMany
    {
        return $this->belongsToMany(Pastry::class);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/ingredients/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add New Ingredient') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <section>
                        <x-error-message :hasErrors="(bool) $errors->count()">{{ __('Ingredient creation failed!') }}</x-error-message>
                        <form method="post" action="{{ route('admin.ingredients.store') }}" class="space-y-6 space-y-reverse">
                            @csrf

                            <div>
                                <x-input-label for="name" :value="__('Name')" />
                                <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', '')" required />
                                <x-input-description>{{ __('Max 256 characters') }}</x-input-description>
                                <x-input-error class="mt-2" :messages="$errors->get('name')" />
                            </div>

                            <div>
                                <x-input-label for="unit-of-measurement" :value="__('Unit of measurement')" />
                                <select id="unit-of-measurement" name="unit_of_measurement" class="border border-gray-300 text-gray-900 rounded-md shadow-sm block flex-none mt-3">
                                    <option value="" @selected(old('unit_of_measurement', '') == '')>{{ __('None') }}</option>
                                    <option value="gr" @selected(old('unit_of_measurement', '') == '')>{{ __('Grams (gr)') }}</option>
                                    <option value="ml" @selected(old('unit_of_measurement', '') == '')>{{ __('Milliliters (ml)') }}</option>
                                </select>
                                <x-input-error class="mt-2" :messages="$errors->get('unit_of_measurement')" />
                            </div>

                            <hr>

                            <div class="flex items-center gap-4">        
                                <x-primary-button>{{ __('Save') }}</x-primary-button>
                                <x-button-link color="light-gray" :href="route('admin.ingredients.index')">{{ __('< Back') }}</x-button-link>
                            </div>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/ingredients/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <small class="block mb-2">{{ __('Edit ingredient:') }}</small>
            <span class="text-gray-500">{{ $ingredient->name }}</span>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <section>
                        <x-error-message :hasErrors="(bool) $errors->count()">{{ __('Ingredient editing failed!') }}</x-error-message>
                        <form method="post" action="{{ route('admin.ingredients.update', $ingredient->id) }}" class="space-y-6 space-y-reverse">
                            @csrf
                            @method('patch')

                            <div>
                                <x-input-label for="name" :value="__('Name')" />
                                <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', $ingredient->name)" required />
                                <x-input-description>{{ __('Max 256 characters') }}</x-input-description>
                                <x-input-error class="mt-2" :messages="$errors->get('name')" />
                            </div>

                            <div>
                                <x-input-label for="unit-of-measurement" :value="__('Unit of measurement')" />
                                <select id="unit-of-measurement" name="unit_of_measurement" class="border border-gray-300 text-gray-900 rounded-md shadow-sm block flex-none mt-3">
                                    <option value="" @selected(old('unit_of_measurement', $ingredient->unit_of_measurement) == '')>{{ __('None') }}</option>
                                    <option value="gr" @selected(old('unit_of_measurement', $ingredient->unit_of_measurement) == 'gr')>{{ __('Grams (gr)') }}</option>
                                    <option value="ml" @selected(old('unit_of_measurement', $ingredient->unit_of_measurement) == 'ml')>{{ __('Milliliters (ml)') }}</option>
                                </select>
                                <x-input-error class="mt-2" :messages="$errors->get('unit_of_measurement')" />
                            </div>

                            <hr>
                            
                            <div class="flex items-center gap-4">        
                                <x-primary-button>{{ __('Save') }}</x-primary-button>
                                <x-button-link color="light-gray" :href="route('admin.ingredients.index')">{{ __('< Back') }}</x-button-link>
                            </div>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/ingredients/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Ingredients List') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <x-succcess-message :success="Session::get('success')">{{ Session::get('success') }}</x-succcess-message>
                    <x-button-link :href="route('admin.ingredients.create')">{{ __('Add new') }}</x-button-link>
                    @if ($ingredients->count())
                    <table class="table-auto w-full mt-6">
                        <thead class="text-left bg-gray-100">
                            <tr>
                                <th class="p-3">{{ __('Name') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($ingredients as $ingredient)
                            <tr class="hover:bg-gray-200">
                                <td class="p-3 border-t border-gray-100 font-semibold">{{ $ingredient['name'] }}</td>
                                <td class="p-3 border-t border-gray-100 text-right">
                                    <x-button-link :href="route('admin.ingredients.edit', $ingredient['id'])" color="blue" size="small">{{ __('Edit') }}</x-button-link>
                                    <form x-data="{}" @submit.prevent x-ref="deleteForm{{$ingredient['id']}}" action="{{ route('admin.ingredients.destroy', $ingredient['id']) }}" method="post" class="inline-block">
                                        @csrf
                                        @method('delete')
                                        <x-danger-button @click="if (confirm('{{ __('Confirm to delete') }}')) $refs.deleteForm{{$ingredient['id']}}.submit();" class="px-2 py-1 font-bold ml-3">{{ __('Delete') }}</x-danger-button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <hr>
                    <div class="mt-8">
                        {{ $ingredients->links() }}
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout>