routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCatalogItemController;
use App\Http\Controllers\Admin\AdminIngredientController;
use App\Http\Controllers\Admin\AdminPastryController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Public routes
 */
Route::get('/', fn() => view('index'))->name('index');

/**
 * Admin routes
 */
Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {

    Route::get('/', fn() => redirect()->route('admin.dashboard'));

    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');

    Route::prefix('profile')->name('profile.')->group(function(){
        Route::get('/', [AdminProfileController::class, 'edit'])->name('edit');
        Route::patch('/', [AdminProfileController::class, 'update'])->name('update');
        Route::delete('/', [AdminProfileController::class, 'destroy'])->name('destroy');
    });

    Route::resource('pastries', AdminPastryController::class, ['except'=> ['show']]);
    Route::resource('ingredients', AdminIngredientController::class, ['except'=> ['show']]);
    Route::resource('catalog-items', AdminCatalogItemController::class, ['except'=> ['show']]);
});

/**
 * Auth routes
 */
require __DIR__.'/auth.php';

app/Models/Pastry.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Pastry extends Model
{
    use HasFactory;
    
    /**
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'price',
    ];

    /**
     * @return BelongsToMany
     */
    public function ingredients(): BelongsToMany
    {
        return $this->belongsToMany(Ingredient::class)->withPivot('quantity');
    }

    /**
     * @return HasMany
     */
    public function notes(): HasMany
    {
        return $this->hasMany(CatalogItem::class); 
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/pastries/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add New Pastry') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <section>
                        <x-error-message :hasErrors="(bool) $errors->count()">{{ __('Pastry creation failed!') }}</x-error-message>
                        <form method="post" action="{{ route('admin.pastries.store') }}" class="space-y-6 space-y-reverse">
                            @csrf

                            <div>
                                <x-input-label for="name" :value="__('Name')" />
                                <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', '')" required />
                                <x-input-description>{{ __('Max 256 characters') }}</x-input-description>
                                <x-input-error class="mt-2" :messages="$errors->get('name')" />
                            </div>

                            <div>
                                <x-input-label for="price" :value="__('Price')" />
                                <x-text-input id="price" name="price" type="number" step="0.01" class="mt-1" :value="old('price', '')" required /><span class="ml-2">€</span>
                                <x-input-description>{{ __('You can insert amount with dot or comma') }}</x-input-description>
                                <x-input-error class="mt-2" :messages="$errors->get('price')" />
                            </div>
                            
                            <h3>{{ __('Ingredients') }}</h3>

                            <div>
                                <x-ingredients-field :ingredients=$ingredients :old_ingredients="old('ingredient', [])" :old_qty="old('qty', [])"></x-ingredients-field>
                            </div>

                            <hr>

                            <div class="flex items-center gap-4">
                                <x-primary-button>{{ __('Save') }}</x-primary-button>
                                <x-button-link color="light-gray" :href="route('admin.pastries.index')">{{ __('< Back') }}</x-button-link>
                            </div>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/pastries/edit.blade.php
<x-app-layout>
    <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <small class="block mb-2">{{ __('Edit pastry:') }}</small>
            <span class="text-gray-500">{{ $pastry->name }}</span>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <section>
                        <x-error-message :hasErrors="(bool) $errors->count()">{{ __('Pastry update failed!') }}</x-error-message>
                        <form method="post" action="{{ route('admin.pastries.update', $pastry->id) }}" class="space-y-6 space-y-reverse">
                            @csrf
                            @method('patch')

                            <div>
                                <x-input-label for="name" :value="__('Name')" />
                                <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', $pastry->name)" required />
                                <x-input-description>{{ __('Max 256 characters') }}</x-input-description>
                                <x-input-error class="mt-2" :messages="$errors->get('name')" />
                            </div>

                            <div>
                                <x-input-label for="price" :value="__('Price')" />
                                <x-text-input id="price" name="price" type="number" step="0.01" class="mt-1" :value="old('price', $pastry->price)" required /><span class="ml-2">€</span>
                                <x-input-description>{{ __('You can insert amount with dot or comma') }}</x-input-description>
                                <x-input-error class="mt-2" :messages="$errors->get('price')" />
                            </div>
                            
                            <h3>{{ __('Ingredients') }}</h3>

                            @php
                            $ingredients_pivot_data = array_column($pastry->ingredients->toArray(), 'pivot');
                            $old_ingredients = array_column($ingredients_pivot_data, 'ingredient_id');
                            $old_qtys = array_column($ingredients_pivot_data, 'quantity');
                            @endphp

                            <div>
                                <x-ingredients-field :ingredients=$ingredients :old_ingredients="old('ingredient', $old_ingredients)" :old_qty="old('qty', $old_qtys)"></x-ingredients-field>
                            </div>

                            <hr>

                            <div class="flex items-center gap-4">
                                <x-primary-button>{{ __('Save') }}</x-primary-button>
                                <x-button-link color="light-gray" :href="route('admin.pastries.index')">{{ __('< Back') }}</x-button-link>
                            </div>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/pastries/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Pastries List') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <x-succcess-message :success="Session::get('success')">{{ Session::get('success') }}</x-succcess-message>
                    <x-button-link :href="route('admin.pastries.create')">{{ __('Add new') }}</x-button-link>
                    @if ($pastries->count())
                    <table class="table-auto w-full mt-6">
                        <thead class="text-left bg-gray-100">
                            <tr>
                                <th class="p-3">{{ __('Name') }}</th>
                                <th class="p-3">{{ __('Price') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($pastries as $pastry)
                            <tr class="hover:bg-gray-200">
                                <td class="p-3 border-t border-gray-100 font-semibold">{{ $pastry['name'] }}</td>
                                <td class="p-3 border-t border-gray-100">{{ Str::replace('.', ',', $pastry['price']) }} €</td>
                                <td class="p-3 border-t border-gray-100 text-right">
                                    <x-button-link :href="route('admin.pastries.edit', $pastry['id'])" color="blue" size="small">{{ __('Edit') }}</x-button-link>
                                    <form x-data="{}" @submit.prevent x-ref="deleteForm{{$pastry['id']}}" action="{{ route('admin.pastries.destroy', $pastry['id']) }}" method="post" class="inline-block">
                                        @csrf
                                        @method('delete')
                                        <x-danger-button @click="if (confirm('{{ __('Confirm to delete') }}')) $refs.deleteForm{{$pastry['id']}}.submit();" class="px-2 py-1 font-bold ml-3">{{ __('Delete') }}</x-danger-button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <hr>
                    <div class="mt-8">
                        {{ $pastries->links() }}
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout>