routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCatalogItemController;
use App\Http\Controllers\Admin\AdminIngredientController;
use App\Http\Controllers\Admin\AdminPastryController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Public routes
 */
Route::get('/', fn() => view('index'))->name('index');

/**
 * Admin routes
 */
Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {

    Route::get('/', fn() => redirect()->route('admin.dashboard'));

    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');

    Route::prefix('profile')->name('profile.')->group(function(){
        Route::get('/', [AdminProfileController::class, 'edit'])->name('edit');
        Route::patch('/', [AdminProfileController::class, 'update'])->name('update');
        Route::delete('/', [AdminProfileController::class, 'destroy'])->name('destroy');
    });

    Route::resource('pastries', AdminPastryController::class, ['except'=> ['show']]);
    Route::resource('ingredients', AdminIngredientController::class, ['except'=> ['show']]);
    Route::resource('catalog-items', AdminCatalogItemController::class, ['except'=> ['show']]);
});

/**
 * Auth routes
 */
require __DIR__.'/auth.php';

app/Models/CatalogItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class CatalogItem extends Model
{
    use HasFactory;

    /**
     * @var array<int, string>
     */
    protected $fillable = [
        'pastry_id',
        'produced_at',
        'quantity',
    ];

    /**
     * @var array<int, string>
     */
    protected $with = [
        'pastry'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'produced_at' => 'date:d-m-Y',
    ];

    /**
     * @return BelongsTo
     */
    public function pastry(): BelongsTo
    {
        return $this->belongsTo(Pastry::class);
    }

    /**
     * Check if a catalog item with same pastry and production date exists.
     *
     * @param integer $pastryId
     * @param string $productionDate
     * @return boolean
     */
    public static function checkDuplicateByPastryAndDate(int $pastryId, string $productionDate): bool
    {
        return self::where('pastry_id', $pastryId)->whereDate('produced_at', $productionDate)->exists();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/catalog-items/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add New Catalog Item') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <section>
                    <x-error-message :hasErrors="(bool) $errors->count()">{{ __('Catalog item creation failed!') }}</x-error-message>
                    <form method="post" action="{{ route('admin.catalog-items.store') }}" class="space-y-6 space-y-reverse">
                        @csrf

                        <div class="flex flex-row space-x-4">
                            <div class="basis-1/4">
                                <x-input-label for="pastry" :value="__('Pastry')" />
                                <select id="pastry" name="pastry_id" class="border border-gray-300 text-gray-900 rounded-md shadow-sm block w-full mt-1" required>
                                    <option value="">{{ __('Select a pastry') }}</option>
                                    @foreach($pastries as $pastry)
                                    <option value="{{ $pastry->id }} @if(old('pastry_id', '') == $pastry->id) selected @endif">{{ $pastry->name }}</option>
                                    @endforeach
                                </select>
                                <x-input-error class="mt-2" :messages="$errors->get('pastry')" />
                            </div>
                            
                            <div class="basis-1/4">
                                <x-input-label for="produced-at" :value="__('Produced at')" />
                                <x-text-input value="{{ now()->format('d-m-Y') }}" id="produced-at" name="produced_at" type="date" class="mt-1 block w-full" :value="old('produced_at', now()->format('Y-m-d'))" required />
                                <x-input-error class="mt-2" :messages="$errors->get('produced_at')" />
                            </div>

                            <div class="basis-1/4">
                                <x-input-label for="quantity" :value="__('Quantity')" />
                                <x-text-input id="quantity" name="quantity" type="number" step="1" min="1" class="mt-1 block w-[100px]" :value="old('quantity', '')" required />
                                <x-input-error class="mt-2" :messages="$errors->get('quantity')" />
                            </div>
                        </div>
                        <x-input-description>{{ __('Note: If you create a catalog item with a pastry and production date already created, they will be aggregated.') }}</x-input-description>

                        <hr>

                        <div class="flex items-center gap-4">        
                            <x-primary-button>{{ __('Save') }}</x-primary-button>
                            <x-button-link color="light-gray" :href="route('admin.catalog-items.index')">{{ __('< Back') }}</x-button-link>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/catalog-items/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <small class="block mb-2">{{ __('Edit catalog item:') }}</small>
            <span class="text-gray-500">{{ $catalogItem->pastry->name }} - {{ $catalogItem->produced_at->format('d/m/Y') }}</span>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <section>
                    <x-error-message :hasErrors="(bool) $errors->count()">{{ __('Catalog item editing failed!') }}</x-error-message>
                    <form method="post" action="{{ route('admin.catalog-items.update', $catalogItem->id) }}" class="space-y-6 space-y-reverse">
                        @csrf
                        @method('patch')

                        <div class="flex flex-row space-x-4">
                            <div class="basis-1/4">
                                <x-input-label for="pastry" :value="__('Pastry')" />
                                <select id="pastry" name="pastry_id" class="border border-gray-300 text-gray-900 rounded-md shadow-sm block w-full mt-1" required>
                                    <option value="">{{ __('Select a pastry') }}</option>
                                    @foreach($pastries as $pastry)
                                    <option value="{{ $pastry->id }}" @if(old('pastry_id', $catalogItem->pastry->id) == $pastry->id) selected @endif">{{ $pastry->name }}</option>
                                    @endforeach
                                </select>
                                <x-input-error class="mt-2" :messages="$errors->get('pastry_id')" />
                            </div>

                            <div class="basis-1/4">
                                <x-input-label for="produced-at" :value="__('Produced at')" />
                                <x-text-input id="produced-at" name="produced_at" type="date" class="mt-1 block w-full" :value="old('produced_at', $catalogItem->produced_at->format('Y-m-d'))" required />
                                <x-input-error class="mt-2" :messages="$errors->get('produced_at')" />
                            </div>

                            <div class="basis-1/4">
                                <x-input-label for="quantity" :value="__('Quantity')" />
                                <x-text-input id="quantity" name="quantity" type="number" step="1" min="1" class="mt-1 block w-[100px]" :value="old('quantity', $catalogItem->quantity)" required />
                                <x-input-error class="mt-2" :messages="$errors->get('quantity')" />
                            </div>
                        </div>
                        <x-input-description>{{ __('Note: If you create a catalog item with a pastry and production date already created, they will be aggregated.') }}</x-input-description>

                        <hr>
                        
                        <div class="flex items-center gap-4">        
                            <x-primary-button>{{ __('Save') }}</x-primary-button>
                            <x-button-link color="light-gray" :href="route('admin.catalog-items.index')">{{ __('< Back') }}</x-button-link>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/catalog-items/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Catalog') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <x-succcess-message :success="Session::get('success')">{{ Session::get('success') }}</x-succcess-message>
                    <x-error-message :hasErrors="Session::get('duplicate_error')">{{ Session::get('duplicate_error') }}</x-error-message>
                    <x-button-link :href="route('admin.catalog-items.create')">{{ __('Add new') }}</x-button-link>
                    @if ($catalog_items->count())
                    <table class="table-auto w-full mt-6">
                        <thead class="text-left bg-gray-100">
                            <tr>
                                <th class="p-3">{{ __('Pastry') }}</th>
                                <th class="p-3">{{ __('Quantity') }}</th>
                                <th class="p-3">{{ __('Production date') }}</th>
                                <th class="p-3">{{ __('Expiry date') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($catalog_items as $item)
                            <tr class="hover:bg-gray-200">
                                <td class="p-3 border-t border-gray-100 font-semibold">{{ $item->pastry->name }}</td>
                                <td class="p-3 border-t border-gray-100 font-semibold"><span class="inline-block py-1 px-2 bg-gray-100 rounded-xl">{{ $item->quantity }}</span></td>
                                <td class="p-3 border-t border-gray-100 font-semibold">{{ $item->produced_at->format('d-m-Y') }}</td>
                                <td class="p-3 border-t border-gray-100 font-semibold"><span class="text-red-600 font-bold">{{ $item->produced_at->addDays(3)->format('d-m-Y') }}</span></td>
                                <td class="p-3 border-t border-gray-100 text-right">
                                    <x-button-link :href="route('admin.catalog-items.edit', $item->id)" color="blue" size="small">{{ __('Edit') }}</x-button-link>
                                    <form x-data="{}" @submit.prevent x-ref="deleteForm{{ $item->id }}" action="{{ route('admin.catalog-items.destroy', $item->id) }}" method="post" class="inline-block">
                                        @csrf
                                        @method('delete')
                                        <x-danger-button @click="if (confirm('{{ __('Confirm to delete') }}')) $refs.deleteForm{{$item->id}}.submit();" class="px-2 py-1 font-bold ml-3">{{ __('Delete') }}</x-danger-button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <hr>
                    <div class="mt-8">
                        {{ $catalog_items->links() }}
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout>